sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.10'
  - '0.12'
  - 4
  - stable
before_install:
  - npm install -g npm@latest
before_script:
  - npm prune
after_success:
  - npm run codecov
