window.esdocSearchIndex = [
  [
    "aws-sdk-config-loader/src/configprovider.js~configprovider",
    "function/index.html#static-function-configProvider",
    "<span>configProvider</span> <span class=\"search-result-import-path\">aws-sdk-config-loader/src/configProvider.js</span>",
    "function"
  ],
  [
    "aws-sdk-config-loader/src/configs/environmentconfigs.js~environmentconfigs",
    "function/index.html#static-function-environmentConfigs",
    "<span>environmentConfigs</span> <span class=\"search-result-import-path\">aws-sdk-config-loader/src/configs/environmentConfigs.js</span>",
    "function"
  ],
  [
    "aws-sdk-config-loader/src/configs/fileconfigs.js~fileconfigs",
    "function/index.html#static-function-fileConfigs",
    "<span>fileConfigs</span> <span class=\"search-result-import-path\">aws-sdk-config-loader/src/configs/fileConfigs.js</span>",
    "function"
  ],
  [
    "aws-sdk-config-loader/src/index.js~loader",
    "function/index.html#static-function-loader",
    "<span>loader</span> <span class=\"search-result-import-path\">aws-sdk-config-loader/src/index.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "loader src/index.js~loader,loader",
    "test-file/test/loader-spec.js.html#lineNumber15",
    "aws-sdk-config-loader",
    "test"
  ],
  [
    "",
    "test-file/test/loader-spec.js.html#lineNumber43",
    "aws-sdk-config-loader override AWS.config",
    "test"
  ],
  [
    "",
    "test-file/test/loader-spec.js.html#lineNumber56",
    "aws-sdk-config-loader when apply options",
    "test"
  ],
  [
    "",
    "test-file/test/loader-spec.js.html#lineNumber88",
    "aws-sdk-config-loader when apply options and apply noReflectCredentials and throw error",
    "test"
  ],
  [
    "",
    "test-file/test/loader-spec.js.html#lineNumber71",
    "aws-sdk-config-loader when apply options and apply noReflectCredentials override only config",
    "test"
  ],
  [
    "",
    "test-file/test/loader-spec.js.html#lineNumber57",
    "aws-sdk-config-loader when apply options override config and credentials",
    "test"
  ],
  [
    "configprovider src/configprovider.js~configprovider,configprovider",
    "test-file/test/configProvider-spec.js.html#lineNumber9",
    "configProvider()",
    "test"
  ],
  [
    "",
    "test-file/test/configProvider-spec.js.html#lineNumber10",
    "configProvider() when apply multiple getteres return overriden config",
    "test"
  ],
  [
    "",
    "test-file/test/configProvider-spec.js.html#lineNumber24",
    "configProvider() when apply options getter args applied options",
    "test"
  ],
  [
    "",
    "test-file/test/configProvider-spec.js.html#lineNumber20",
    "configProvider() when doesnot apply getters return default config",
    "test"
  ],
  [
    "environmentconfigs src/configs/environmentconfigs.js~environmentconfigs,environmentconfigs",
    "test-file/test/configs/environmentConfigs-spec.js.html#lineNumber8",
    "environmentConfigs()",
    "test"
  ],
  [
    "",
    "test-file/test/configs/environmentConfigs-spec.js.html#lineNumber30",
    "environmentConfigs() when AMAZON_REGION and AWS_REGION exists return overriden config by AWS_REGION",
    "test"
  ],
  [
    "",
    "test-file/test/configs/environmentConfigs-spec.js.html#lineNumber25",
    "environmentConfigs() when env.AMAZON_REGION exists return overriden config",
    "test"
  ],
  [
    "",
    "test-file/test/configs/environmentConfigs-spec.js.html#lineNumber20",
    "environmentConfigs() when env.AWS_REGION exists return overriden config",
    "test"
  ],
  [
    "",
    "test-file/test/configs/environmentConfigs-spec.js.html#lineNumber16",
    "environmentConfigs() when no specific env return default config",
    "test"
  ],
  [
    "fileconfigs src/configs/fileconfigs.js~fileconfigs,fileconfigs",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber11",
    "fileConfigs()",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber26",
    "fileConfigs() return default profile config",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber74",
    "fileConfigs() when apply opts.configFile return config from opts.configFile",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber67",
    "fileConfigs() when apply opts.profile return config using opts.profile",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber49",
    "fileConfigs() when config file doesnot exists return default config",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber37",
    "fileConfigs() when default profile doesnot exists in file return default config",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber30",
    "fileConfigs() when env.HOME and env.AWS_CONFIG_FILE doesnot exists return default config",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber44",
    "fileConfigs() when set env.AWS_CONFIG_FILE return config from specific file",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber56",
    "fileConfigs() when set env.AWS_PROFILE",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber61",
    "fileConfigs() when set env.AWS_PROFILE and profile doesnot exists in file return default config",
    "test"
  ],
  [
    "",
    "test-file/test/configs/fileConfigs-spec.js.html#lineNumber57",
    "fileConfigs() when set env.AWS_PROFILE and profile exists in file return specific profile config",
    "test"
  ],
  [
    "src/configprovider.js",
    "file/src/configProvider.js.html",
    "src/configProvider.js",
    "file"
  ],
  [
    "src/configs/environmentconfigs.js",
    "file/src/configs/environmentConfigs.js.html",
    "src/configs/environmentConfigs.js",
    "file"
  ],
  [
    "src/configs/fileconfigs.js",
    "file/src/configs/fileConfigs.js.html",
    "src/configs/fileConfigs.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "test/configprovider-spec.js",
    "test-file/test/configProvider-spec.js.html",
    "test/configProvider-spec.js",
    "testFile"
  ],
  [
    "test/configs/environmentconfigs-spec.js",
    "test-file/test/configs/environmentConfigs-spec.js.html",
    "test/configs/environmentConfigs-spec.js",
    "testFile"
  ],
  [
    "test/configs/fileconfigs-spec.js",
    "test-file/test/configs/fileConfigs-spec.js.html",
    "test/configs/fileConfigs-spec.js",
    "testFile"
  ],
  [
    "test/loader-spec.js",
    "test-file/test/loader-spec.js.html",
    "test/loader-spec.js",
    "testFile"
  ]
]